-- MySQL Script generated by MySQL Workbench
-- Tue Jan  6 21:28:09 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dunk_contest
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dunk_contest` ;

-- -----------------------------------------------------
-- Schema dunk_contest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dunk_contest` ;
USE `dunk_contest` ;

-- -----------------------------------------------------
-- Table `dunk_contest`.`Dunks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dunk_contest`.`Dunks` ;

CREATE TABLE IF NOT EXISTS `dunk_contest`.`Dunks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `dunk_contest`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dunk_contest`.`Players` ;

CREATE TABLE IF NOT EXISTS `dunk_contest`.`Players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(100) NOT NULL,
  `Lastname` VARCHAR(100) NOT NULL,
  `Team` VARCHAR(100) NULL DEFAULT NULL,
  `Height` DECIMAL(3,2) NULL,
  `id_dunk` INT NOT NULL,
  `date_added` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_player_dunk` (`id_dunk` ASC) VISIBLE,
  CONSTRAINT `fk_player_dunk`
    FOREIGN KEY (`id_dunk`)
    REFERENCES `dunk_contest`.`Dunks` (`id`));


-- -----------------------------------------------------
-- Table `dunk_contest`.`Judges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dunk_contest`.`Judges` ;

CREATE TABLE IF NOT EXISTS `dunk_contest`.`Judges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(100) NOT NULL,
  `Lastname` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(150) NULL DEFAULT NULL,
  `Status` VARCHAR(50) NULL,
  `Created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`Email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `dunk_contest`.`Contests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dunk_contest`.`Contests` ;

CREATE TABLE IF NOT EXISTS `dunk_contest`.`Contests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Year` INT NULL DEFAULT NULL,
  `Location` VARCHAR(150) NULL DEFAULT NULL,
  `Contest_date` DATE NULL DEFAULT NULL,
  `Created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `dunk_contest`.`Contest_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dunk_contest`.`Contest_players` ;

CREATE TABLE IF NOT EXISTS `dunk_contest`.`Contest_players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_contest` INT NOT NULL,
  `id_player` INT NOT NULL,
  `Position` INT NULL DEFAULT NULL,
  `Qualified_for_final` TINYINT NULL DEFAULT NULL,
  `Final_rank` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_contest_player` (`id_contest` ASC, `id_player` ASC) VISIBLE,
  INDEX `fk_cp_contest` (`id_contest` ASC) VISIBLE,
  INDEX `fk_cp_player` (`id_player` ASC) VISIBLE,
  CONSTRAINT `fk_cp_contest`
    FOREIGN KEY (`id_contest`)
    REFERENCES `dunk_contest`.`Contests` (`id`),
  CONSTRAINT `fk_cp_player`
    FOREIGN KEY (`id_player`)
    REFERENCES `dunk_contest`.`Players` (`id`));


-- -----------------------------------------------------
-- Table `dunk_contest`.`Contest_judges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dunk_contest`.`Contest_judges` ;

CREATE TABLE IF NOT EXISTS `dunk_contest`.`Contest_judges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_contest` INT NOT NULL,
  `id_judge` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_contest_judge` (`id_contest` ASC, `id_judge` ASC) VISIBLE,
  INDEX `fk_cj_contest` (`id_contest` ASC) VISIBLE,
  INDEX `fk_cj_judge` (`id_judge` ASC) VISIBLE,
  CONSTRAINT `fk_cj_contest`
    FOREIGN KEY (`id_contest`)
    REFERENCES `dunk_contest`.`Contests` (`id`),
  CONSTRAINT `fk_cj_judge`
    FOREIGN KEY (`id_judge`)
    REFERENCES `dunk_contest`.`Judges` (`id`));


-- -----------------------------------------------------
-- Table `dunk_contest`.`Attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dunk_contest`.`Attempts` ;

CREATE TABLE IF NOT EXISTS `dunk_contest`.`Attempts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_contest` INT NOT NULL,
  `id_player` INT NOT NULL,
  `Round_number` INT NOT NULL,
  `Attempt_number` INT NOT NULL,
  `id_dunk` INT NOT NULL,
  `Average_score` DECIMAL(4,2) NULL DEFAULT NULL,
  `Created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_attempt` (`id_contest` ASC, `id_player` ASC, `Round_number` ASC, `Attempt_number` ASC) VISIBLE,
  INDEX `fk_attempt_contest` (`id_contest` ASC) VISIBLE,
  INDEX `fk_attempt_player` (`id_player` ASC) VISIBLE,
  INDEX `fk_attempt_dunk` (`id_dunk` ASC) VISIBLE,
  CONSTRAINT `fk_attempt_contest`
    FOREIGN KEY (`id_contest`)
    REFERENCES `dunk_contest`.`Contests` (`id`),
  CONSTRAINT `fk_attempt_player`
    FOREIGN KEY (`id_player`)
    REFERENCES `dunk_contest`.`Players` (`id`),
  CONSTRAINT `fk_attempt_dunk`
    FOREIGN KEY (`id_dunk`)
    REFERENCES `dunk_contest`.`Dunks` (`id`));


-- -----------------------------------------------------
-- Table `dunk_contest`.`Scores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dunk_contest`.`Scores` ;

CREATE TABLE IF NOT EXISTS `dunk_contest`.`Scores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_attempt` INT NOT NULL,
  `id_judge` INT NOT NULL,
  `Score` DECIMAL(4,2) NOT NULL,
  `Created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_attempt_judge` (`id_attempt` ASC, `id_judge` ASC) VISIBLE,
  INDEX `fk_score_attempt` (`id_attempt` ASC) VISIBLE,
  INDEX `fk_score_judge` (`id_judge` ASC) VISIBLE,
  CONSTRAINT `fk_score_attempt`
    FOREIGN KEY (`id_attempt`)
    REFERENCES `dunk_contest`.`Attempts` (`id`),
  CONSTRAINT `fk_score_judge`
    FOREIGN KEY (`id_judge`)
    REFERENCES `dunk_contest`.`Judges` (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
