-- MySQL Script generated by MySQL Workbench
-- Fri Nov 14 14:52:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjDBPy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProjDBPy` ;

-- -----------------------------------------------------
-- Schema ProjDBPy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjDBPy` DEFAULT CHARACTER SET utf8 ;
USE `ProjDBPy` ;

-- -----------------------------------------------------
-- Table `ProjDBPy`.`Dunks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjDBPy`.`Dunks` ;

CREATE TABLE IF NOT EXISTS `ProjDBPy`.`Dunks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  `Average_rating` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjDBPy`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjDBPy`.`Players` ;

CREATE TABLE IF NOT EXISTS `ProjDBPy`.`Players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `Team` VARCHAR(45) NULL,
  `Height` DECIMAL(2) NULL,
  `Dunks_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Players_Dunks1_idx` (`Dunks_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Players_Dunks1`
    FOREIGN KEY (`Dunks_id`)
    REFERENCES `ProjDBPy`.`Dunks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjDBPy`.`Judges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjDBPy`.`Judges` ;

CREATE TABLE IF NOT EXISTS `ProjDBPy`.`Judges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjDBPy`.`Rounds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjDBPy`.`Rounds` ;

CREATE TABLE IF NOT EXISTS `ProjDBPy`.`Rounds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Round_number` INT NOT NULL,
  `Dunks_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Rounds_Dunks1_idx` (`Dunks_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Rounds_Dunks1`
    FOREIGN KEY (`Dunks_id`)
    REFERENCES `ProjDBPy`.`Dunks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjDBPy`.`Concours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjDBPy`.`Concours` ;

CREATE TABLE IF NOT EXISTS `ProjDBPy`.`Concours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Year` INT NOT NULL,
  `Place` VARCHAR(45) NOT NULL,
  `Date` DATE NULL,
  `Rounds_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Concours_Rounds1_idx` (`Rounds_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Concours_Rounds1`
    FOREIGN KEY (`Rounds_id`)
    REFERENCES `ProjDBPy`.`Rounds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjDBPy`.`Judges_has_Dunks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjDBPy`.`Judges_has_Dunks` ;

CREATE TABLE IF NOT EXISTS `ProjDBPy`.`Judges_has_Dunks` (
  `Judges_id` INT NOT NULL,
  `Dunks_id` INT NOT NULL,
  `Rating` INT NOT NULL,
  PRIMARY KEY (`Judges_id`, `Dunks_id`),
  INDEX `fk_Judges_has_Dunks_Dunks1_idx` (`Dunks_id` ASC) VISIBLE,
  INDEX `fk_Judges_has_Dunks_Judges_idx` (`Judges_id` ASC) VISIBLE,
  CONSTRAINT `fk_Judges_has_Dunks_Judges`
    FOREIGN KEY (`Judges_id`)
    REFERENCES `ProjDBPy`.`Judges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Judges_has_Dunks_Dunks1`
    FOREIGN KEY (`Dunks_id`)
    REFERENCES `ProjDBPy`.`Dunks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
